apiVersion: apps/v1
kind: Deployment
metadata:
  name: minha-aplicacao
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minha-aplicacao
  template:
    metadata:
      labels:
        app: minha-aplicacao
    spec:
      containers:
        - name: minha-aplicacao
          image: nome-da-sua-imagem:tag
          ports:
            - containerPort: 8080  # Porta em que sua aplicação está ouvirá dentro do container
