apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  selector:
    app: redis
  ports:
    - name: amqp
      protocol: TCP
      port: 6379
      targetPort: 6379
    - name: management
      protocol: TCP
      port: 8001
      targetPort: 8001
