apiVersion: v1
kind: Service
metadata:
  name: minha-aplicacao-service
spec:
  selector:
    app: minha-aplicacao
  ports:
    - protocol: TCP
      port: 80  # Porta que você deseja expor
      targetPort: 8080  # Porta do container
  type: LoadBalancer  # Tipo de serviço. Pode ser ClusterIP, NodePort, LoadBalancer, etc.
