FROM python:3.9

WORKDIR /app2

COPY * /app2/

RUN apt-get install -y git && \
    pip install -r requirements.txt 

#ENTRYPOINT ["python3", "consumer.py"]
ENTRYPOINT ["python3", "-u", "consumer.py"]
